services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      PostgreUser: ${PostgreUser}
      PostgrePassword: ${PostgrePassword}
      PostgreHost: ${PostgreHost}
    ports:
      - "${PostgrePort}:5432"
    networks:
      - Network
    healthcheck:
      test : ["CMD-SHELL", "pg_isready -U ${PostgreUser} -d ${PostgreName}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: always
    ports:
      - "${Backend_Port}:3301"
    environment:
      - PostgreUser=${PostgreUser}
      - PostgrePassword=${PostgrePassword}
      - PostgreHost=${PostgreHost}
      - PostgrePort=${PostgrePort}
      - PostgreName=${PostgreName}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - Network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "${Frontend_Port}:3300"
    environment:
      Backend_API_URL: ${Backend_API_URL}
      Frontend_Port: ${Frontend_Port}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:Z
      - /app/node_module
    networks:
      - Network


volumes:
  db:

networks:
  Network: